GET_DATA_SUCCESS_CODE = 'GET_DATA_SUCCESS_CODE'
UPDATE_DATA_SUCCESS_CODE = 'UPDATE_DATA_SUCCESS_CODE'
DELETE_DATA_SUCCESS_CODE = 'DELETE_DATA_SUCCESS_CODE'
CREATE_DATA_SUCCESS_CODE = 'CREATE_DATA_SUCCESS_CODE'

DATA_EXIST_EXPECTED_CODE = 'DATA_EXIST_EXPECTED_CODE'

DATA_NOT_FOUND_CODE = 'DATA_NOT_FOUND_CODE'
SERVER_ERROR_CODE = 'SERVER_ERROR_CODE'
PERMISSOION_ERROR_CODE = 'PERMISSOION_ERROR_CODE'
